const { plot1 } = require('../../Analytics/Faculty/AllStudentsConsistency')
const { plot2 } = require('../../Analytics/Faculty/AllStudentsMarks')
const { plot3 } = require('../../Analytics/Faculty/calculateConsistencyScore')
const { plot4 } = require('../../Analytics/Faculty/ConsistencyQue')
const { plot5 } = require('../../Analytics/Faculty/MarksDistribution')
const { plot6 } = require('../../Analytics/Faculty/PieChart')
const { plot7 } = require('../../Analytics/js/SelfVsClassAvg')
const { plot8 } = require('../../Analytics/js/SelfVsClassCourse')
const { plot9 } = require('../../Analytics/Student/ConsistencyProgressBar')
const { plot10 } = require('../../Analytics/Student/SelfVsPeerMarks')
console.log('ploter')
const Router = require('express').Router()

Router.get('/plot1', plot1)
Router.get('/plot2', plot2)
Router.get('/plot3', plot3)
Router.get('/plot4', plot4)
Router.get('/plot5', plot5)
Router.get('/plot6', plot6)
Router.get('/plot7', plot7)
Router.get('/plot8', plot8)
Router.get('/plot9', plot9)
Router.get('/plot10', plot10)
module.exports = Router
